spring:
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jdbc:
    config:
      url: jdbc:h2:file:./database/rant
      username: root
      password: test
      driver-class-name: org.h2.Driver
      show-sql: false
      ddl-auto: "update"
      packageNames: wxdgaming.spring.boot.rant.entity.bean


